name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs: 
  check-app:
    runs-on: ubuntu-latest
    steps: # Utilizo o uses para rodar actions e o run para rodar comandos
      - uses: actions/checkout@v2 # Busca os dados que acabaram de subir e baixa na máquina ubuntu
      - uses: actions/setup-go@v2 # Estou pegando uma action que já existe e foi criada por outro usuário e disponibilizada via github marketplace 
        with: 
          go-version: 1.15
      - run: go test
      - run: go run math.go